import IconGame from 'public/assets/icons/game.svg'
import IconAddressBook from 'public/assets/icons/addressBook.svg'
import IconBadge from 'public/assets/icons/badge.svg'
import IconBrands from 'public/assets/icons/brands.svg'
import IconCash from 'public/assets/icons/cash.svg'
import IconChecked from 'public/assets/icons/checked.svg'
import IconComment from 'public/assets/icons/comment.svg'
import IconDigger from 'public/assets/icons/digger.svg'
import IconFile from 'public/assets/icons/file.svg'
import IconFileImage from 'public/assets/icons/fileImage.svg'
import IconGlobe from 'public/assets/icons/globe.svg'
import IconHome from 'public/assets/icons/home.svg'
import IconList from 'public/assets/icons/list.svg'
import IconMarathon from 'public/assets/icons/marathon.svg'
import IconOrders from 'public/assets/icons/orders.svg'
import IconPoop from 'public/assets/icons/poop.svg'
import IconPrayer from 'public/assets/icons/prayer.svg'
import IconQrcode from 'public/assets/icons/qrcode.svg'
import IconRestroom from 'public/assets/icons/restroom.svg'
import IconSearch from 'public/assets/icons/search.svg'
import IconStore from 'public/assets/icons/store.svg'
import IconUnicorn from 'public/assets/icons/unicorn.svg'
import IconMinusCircle from 'public/assets/icons/minusCircle.svg'
import IconDnd from 'public/assets/icons/dnd.svg'
import IconArrowUpDown from 'public/assets/icons/arrowUpDown.svg'
import IconEye from 'public/assets/icons/eye.svg'
import IconCode from 'public/assets/icons/code.svg'
import IconBox from 'public/assets/icons/box.svg'
import IconSave from 'public/assets/icons/save.svg'
import IconTrash from 'public/assets/icons/trash.svg'
import IconEyeCrossed from 'public/assets/icons/eyeCrossed.svg'
import IconArrowUp from 'public/assets/icons/arrowUp.svg'
import IconArrowLeft from 'public/assets/icons/arrowLeft.svg'
import IconArrowRight from 'public/assets/icons/arrowRight.svg'
import IconArrowDown from 'public/assets/icons/arrowDown.svg'
import IconPlusInSquare from 'public/assets/icons/plusInSquare.svg'
import IconMinusInSquare from 'public/assets/icons/minusInSquare.svg'
import IconExternalLink from 'public/assets/icons/externalLink.svg'
import IconPen from 'public/assets/icons/pen.svg'
import IconTooltip from 'public/assets/icons/tooltip.svg'
import IconClose from 'public/assets/icons/close.svg'
import IconPlus from 'public/assets/icons/plus.svg'


// ts-prune-ignore-next
export {IconGame, IconCode, IconAddressBook, IconBadge, IconBrands, IconCash, IconChecked, IconComment, IconDigger, IconFile, IconFileImage, IconGlobe, IconHome, IconList, IconMarathon, IconOrders, IconPoop, IconPrayer, IconQrcode, IconRestroom, IconSearch, IconStore, IconUnicorn, IconArrowDown, IconExternalLink, IconPen, IconTooltip, IconClose, IconPlus, IconMinusCircle, IconDnd, IconArrowUpDown, IconEye, IconBox, IconSave, IconTrash, IconEyeCrossed, IconArrowLeft, IconArrowRight, IconArrowUp, IconPlusInSquare, IconMinusInSquare}




